---

- name: install apache
  become: True
  apt:
    name:
      - apache2
      - apache2-utils
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: add SWITCH-AAI repo
  become: True
  block:
    - apt_key:
        data: "{{ lookup('file', 'SWITCHaai-swdistrib.asc') }}"
        state: present
    - apt_repository:
        repo: deb http://pkg.switch.ch/switchaai/debian {{ ansible_distribution_release }} main
        state: present
        filename: switchaai
      notify: apt update cache
  when: apache_aai|bool and apache_aai_use_switch_repo|bool

- name: Install SWITCH-AAI
  become: True
  apt:
    name:
      - shibboleth-sp-utils
      - libapache2-mod-shib
    state: present
    update_cache: yes
    cache_valid_time: 1800
    install_recommends: yes
  when: apache_aai|bool

- name: copy base configuration
  become: True
  template:
    src: "000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload apache

- name: copy vhost configuration
  become: True
  template:
    src: "vhosts.conf.j2"
    dest: "/etc/apache2/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: reload apache
  when: apache_create_vhosts|bool

- name: enable/disable apache modules
  become: True
  apache2_module:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present")}}'
  with_items: "{{ apache_modules }}"

- name: enable/disable apache sites
  become: True
  file:
    src: "/etc/apache2/sites-available/{{ item.name }}"
    dest: "/etc/apache2/sites-enabled/{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ apache_sites }}"
  notify: reload apache

- name: Upload shibboleth configuration
  become: True
  copy:
    content: "{{ lookup('file', apache_aai_config_loc + '/' + item ) }}"
    dest: "/etc/shibboleth/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - shibboleth2.xml
    - SWITCHaaiRootCA.crt.pem
    - attribute-map.xml
    - attribute-policy.xml
  when: apache_aai|bool

- name: Check whether shibboleth key has been generated
  become: True
  stat:
    path: /etc/shibboleth/sp-cert.pem
  register: shibcert
  when: apache_aai|bool

- name: Generate shibboleth certificate
  become: True
  command: shib-keygen -f -u _shibd -h {{ ansible_fqdn }} -y 3 -e https://{{ ansible_fqdn }}/shibboleth -o /etc/shibboleth/
  when: apache_aai and not shibcert.stat.exists

- name: Concat shibboleth proxy server certs
  when: apache_aai_clustered | bool
  become: True
  assemble:
    src: /etc/haproxy/shib-proxy-server
    dest: /etc/haproxy/shib-proxy-server.pem
    owner: root
    group: root
    mode: 0640
  notify: restart haproxy

- name: Concat shibboleth proxy client certs
  become: True
  when: apache_aai_clustered | bool
  assemble:
    src: /etc/haproxy/shib-proxy-client
    dest: /etc/haproxy/shib-proxy-client.pem
    owner: root
    group: root
    mode: 0640
  notify: restart haproxy

- name: Add haproxy drop-in
  become: True
  when: apache_aai_clustered | bool
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/conf.d/90-shibd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy
